2025-04-09 18:37:45,794 [INFO] django.authentication: LOGIN: User saavan333 from IP 127.0.0.1
2025-04-09 18:37:47,273 [INFO] django.authentication: LOGOUT: User saavan333 from IP 127.0.0.1
2025-04-09 18:37:52,971 [WARNING] django.authentication: FAILED LOGIN for saavan333 from IP 127.0.0.1
2025-04-09 18:38:02,134 [INFO] django.authentication: LOGIN: User abcd_123 from IP 127.0.0.1
2025-04-09 18:38:03,670 [INFO] django.authentication: LOGOUT: User abcd_123 from IP 127.0.0.1
2025-04-09 19:12:07,923 [INFO] django.authentication: LOGIN: User ssss@111 from IP 127.0.0.1
2025-04-09 19:14:41,612 [ERROR] django.request: Internal Server Error: /accounts/logintoken
Traceback (most recent call last):
  File "C:\Users\Devesh\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Devesh\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Devesh\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Devesh\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
    ...<9 lines>...
    )
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/accounts/logintoken/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
